### ISSUE TITLE
Error when finding references within context of a method body

### ISSUE THREAD

**Issue by AdaTheDev** [mattwhitfield/VisualFindReferences#10]
**Describe the bug**
Error when you "Visual Find References..." from within the context of a method body.
![image](https://user-images.githubusercontent.com/232673/184876425-09ee703e-5462-4b67-8dc0-432888c5cccf.png)

**To Reproduce**
1. Right click the opening brace line, or within the body of a method
2. Select "Visual Find References..."
3. Error pops up, like example screenshot above

**Additional context**
All fine if I right click a method name as the context, but would expect within the context of a method body that it would find references to that method.

Version: 0.37.0.0

**Comment by mattwhitfield** [comment]
Fixed in 0.39 - I didn't do an exhaustive search of 'which syntax node types can we try traversing to parents for' - so if you do find any other please do let me know :)
