### ISSUE TITLE
Can not find any references.

### ISSUE THREAD

**Issue by JOMOGO** [mattwhitfield/VisualFindReferences#27]
**Describe the bug**
No new connections found while they do exist.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/39162984/220366949-6478264a-fb1a-4a90-b5e3-02335fc950f9.png">

**To Reproduce**
Click on find visual references.

**Additional context**
```
public class TestQuery : ITestResourceQuery<PagedResult<Test>>, IPagingOptions
{
        public bool? TestBool{ get; set; }
```

**Comment by mattwhitfield** [comment]
Hi - I'm sorry but I need a bit more context - what are you clicking on in the source code? Where do you expect to see references? Is there a simple repro that demonstrates the problem?

**Comment by mattwhitfield** [comment]
Given the lack of detail, there's not much I can do about this. Please feel free to re-open the issue with more details if you can find a repro 👍
