### ISSUE TITLE
Error Occurred when running on Unreal source, Visual Studio 2022 17.9.4

### ISSUE THREAD

**Issue by geekrelief** [mattwhitfield/VisualFindReferences#36]
When executing the Visual Find References in Visual Studio 2022 17.9.4 I get an error. 

https://github.com/mattwhitfield/VisualFindReferences/assets/27040/ba463b3e-fb46-494d-a8ac-7a99342d6b61

![devenv_lvRavOo3ur](https://github.com/mattwhitfield/VisualFindReferences/assets/27040/b71a1629-901d-42b2-b746-8e8b9670c21f)

I'm running this on the Unreal source.

**Comment by mattwhitfield** [comment]
Hi

Thanks for the video - it will actually only work on C# code... I do have an item already to make it only show up on C# files - just I haven't got round to it yet...

Thanks!

**Comment by geekrelief** [comment]
That's unfortunate. I remember years ago there was an experimental visual tool for navigating a huge code base that supposedly was bought out by MS, but it never materialized into anything. I was hoping yours might do the trick. Do you know of any other tools that might work for a C++ codebase?

**Comment by mattwhitfield** [comment]
Sorry, I am not aware of anything like it that is free. I think there are a bunch of 'enterprise' kind of tools that are waaay too expensive.
